### ISSUE TITLE
in Sveltkit extended colors is not working

### ISSUE THREAD

**Issue by moisesbites** [windicss/windicss-intellisense#92]
I wrote this colors in `windi.config.cjs`:
```JS
module.exports = {
  theme: {
    container: {
      center: true
    },
    extend: {
      colors: {
        white: '#ffffff',
        'gray-lightest': '#f8f8f9',
        'gray-lighter': '#e4e4e5',
        'gray-light': '#d0d1d1',

        gray: '#bebebf',
        'gray-dark': '#969697',
        'gray-darker': '#6e6f6f',
        'gray-darkest': '#484849',
        black: '#202021',

        'primary-light': '#cacfe3',
        primary: '#1a4c8f',
        'primary-dark': '#192846',

        'secundary-light': '#eac7c0',
        secundary: '#8f231a',
        'secundary-dark': '#481911',

        'info-light': '#d7eff9',
        info: '#33bee8',
        'info-dark': '#275b6d',

        'warning-light': '#faeed1',
        warning: '#dbbd45',
        'warning-dark': '#695a27',

        'success-light': '#d7f3d6',
        success: '#47cc5d',
        'success-dark': '#2b6131',

        'danger-light': '#fed2d1',
        danger: '#dd4054',
        'danger-dark': '#6a262c'
      }
    }
  },
  variants: {},
  plugins: []
};
```

In `sevelte.config.cjs`:

```JS
/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	preprocess: [
		windicss({
			kit: true,
			config: "windi.config.cjs",
		}),
	],
	kit: {
.....
```

When I need to use text-primary the extended color is not working:

And in Code editor, the colors is not present in the list:
![image](https://user-images.githubusercontent.com/8934577/115123212-039f3200-9f8a-11eb-85e9-38ddd28ba8c1.png)

**Comment by alexanderniebuhr** [comment]
have you installed windicss as a dependency?

**Comment by moisesbites** [comment]
> have you installed windicss as a dependency?
Yes. I installed using https://github.com/svelte-add/windicss:

```YAML
  "devDependencies": {
    "@sveltejs/adapter-node": "next",
    "@sveltejs/kit": "next",
    "eslint": "^7.24.0",
    "eslint-config-prettier": "^8.2.0",
    "eslint-plugin-svelte3": "^3.1.2",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "svelte": "^3.37.0",
    "svelte-windicss-preprocess": "^3.5.3",
    "vite": "^2.1.5",
    "windicss": "^2.5.14"
  }
```
> Could you also include the output in VSCode Output Panel?

```fileMap: [{"extension":"css","patterns":[{"regex":{},"splitCharacter":" "}]},{"extension":"sass","patterns":[{"regex":{},"splitCharacter":" "}]},{"extension":"less","patterns":[{"regex":{},"splitCharacter":" "}]},{"extension":"javascript","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]},{"extension":"javascriptreact","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]},{"extension":"typescriptreact","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]},{"extension":"html","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]},{"extension":"php","patterns":[{"regex":{},"splitCharacter":" "}]},{"extension":"vue","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]},{"extension":"svelte","patterns":[{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "},{"regex":{},"splitCharacter":" "}]}]
Windi CSS Intellisense is now active!
```
